Repository jenkinsci/azure-ad-plugin, pull requests merged in 2021-03, with the labels that each got.

#79 fixed some deprecation warnings in respect to jenkins.getInstance()
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixFolderProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdUser.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAuthFailAction.java
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
Labels: chore

#77 Fix Security Realm AAD verify failed bug
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
  src/test/java/com/microsoft/jenkins/azuread/AzureAdConfigurationSaveTest.java
  src/test/java/com/microsoft/jenkins/azuread/AzureSecurityRealmTest.java
Labels: bug

#110 Documentation fixes
  README.md
Labels: documentation

#99 [JENKINS-64858] - Enabled support for Job DSL plugin
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixFolderProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixProperty.java
Labels: enhancement

#111 Enable automatic release on merge to master
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/extensions.xml
  .mvn/maven.config
  CHANGELOG-old.md
  checkstyle.xml
  pom.xml
  src/main/java/com/microsoft/jenkins/azuread/AzureAdGroup.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdUser.java
  src/main/java/com/microsoft/jenkins/azuread/scribe/AzureJsonTokenExtractor.java
  src/main/java/com/microsoft/jenkins/azuread/scribe/AzureOAuthService.java
  src/main/java/com/microsoft/jenkins/azuread/scribe/AzureToken.java
Labels: chore
