Repository jenkinsci/azure-ad-plugin, pull requests merged in 2021-04, with the labels that each got.

#113 Cleanup deprecated API usage
  pom.xml
  src/main/java/com/microsoft/jenkins/azuread/AzureAdGroup.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdPlugin.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdUser.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAuthenticationToken.java
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
  src/test/java/com/microsoft/jenkins/azuread/AzureAdConfigurationSaveTest.java
  src/test/java/com/microsoft/jenkins/azuread/AzureSecurityRealmTest.java
Labels: chore

#112 Fix Jenkins API integration
  src/main/java/com/microsoft/jenkins/azuread/AzureAdUser.java
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/config.jelly
  src/main/webapp/help/help-cache-duration.html
Labels: bug

#117 Remove unset given/surname, set mail to upn if to mail sent
  src/main/java/com/microsoft/jenkins/azuread/AzureAdUser.java
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
Labels: chore

#119 Sync UI for Azure AD matrix auth with upstream matrix auth
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config.jelly
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_da.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_de.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_es.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_fi.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_fr.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_ja.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_nb_NO.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_nl.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_pt_BR.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_ru.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_sv_SE.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_tr.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_zh_CN.properties
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config_zh_TW.properties
Labels: enhancement

#118 Upgrade to MSAL
  README.md
  pom.xml
  src/main/java/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdUser.java
  src/main/java/com/microsoft/jenkins/azuread/AzureCachePool.java
  src/main/java/com/microsoft/jenkins/azuread/AzureEnvironment.java
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
  src/main/java/com/microsoft/jenkins/azuread/Constants.java
  src/main/java/com/microsoft/jenkins/azuread/scribe/AzureApi.java
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/config.jelly
Labels: enhancement

#122 Fix add button not working in matrix
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config.jelly
Labels: bug
