Repository jenkinsci/azure-ad-plugin, pull requests merged in 2021-06, with the labels that each got.

#135 Move js to file
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config.jelly
  src/main/resources/com/microsoft/jenkins/azuread/table.js
Labels: chore

#136 Use People-Picker from Microsoft Graph Toolkit for selecting users/group
  .gitignore
  .mvn_exec_node
  README.md
  package-lock.json
  package.json
  pom.xml
  src/main/frontend/index.ts
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixFolderProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdGroupDetails.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy.java
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
  src/main/java/com/microsoft/jenkins/azuread/GraphProxy.java
  src/main/java/com/microsoft/jenkins/azuread/Utils.java
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config.jelly
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/config.jelly
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/help-disableGraphIntegration.html
  src/main/resources/com/microsoft/jenkins/azuread/table.js
  tsconfig.json
  webpack.config.js
Labels: enhancement

#140 Only use security groups as authorities (regression in SDK upgrade)
  pom.xml
  src/main/java/com/microsoft/jenkins/azuread/AzureCachePool.java
Labels: bug

#142 Remove inline css & fix bug allowing removing anonymous user
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config.jelly
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config.properties
  src/main/resources/com/microsoft/jenkins/azuread/table.js
  src/main/webapp/css/azure-ad.css
Labels: bug, enhancement

#141 Fix group icon not displaying when validating groups
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
Labels: bug

#143 Add support for node properties
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixNodeProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy.java
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
  src/main/java/com/microsoft/jenkins/azuread/GraphProxy.java
  src/main/java/com/microsoft/jenkins/azuread/integrations/casc/AzureAdAuthorizationMatrixNodePropertyConfigurator.java
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixNodeProperty/config.groovy
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixProperty/config.groovy
  src/test/java/com/microsoft/jenkins/azuread/integrations/casc/ConfigAsCodeTest.java
  src/test/resources/com/microsoft/jenkins/azuread/integrations/casc/configuration-as-code.yml
Labels: enhancement

#144 Refactoring: Minor test cleanup
  src/test/java/com/microsoft/jenkins/azuread/AzureSecurityRealmTest.java
  src/test/java/com/microsoft/jenkins/azuread/integrations/casc/ConfigAsCodeTest.java
Labels: chore

#147 Use AbstractItem for attaching GraphProxy to job
  src/main/java/com/microsoft/jenkins/azuread/GraphProxy.java
Labels: bug

#149 Add support for display name to loadGroupByGroupName
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
  src/main/java/com/microsoft/jenkins/azuread/utils/UUIDValidator.java
  src/test/java/com/microsoft/jenkins/azuread/utils/UUIDValidatorTest.java
Labels: bug

#150 Add instanceof check for disable graph integration
  src/main/java/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy.java
Labels: bug

#151 Trigger re-authentication when id_token missing
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
Labels: enhancement

#152 Remove filter on security group only
  src/main/java/com/microsoft/jenkins/azuread/AzureCachePool.java
Labels: enhancement
