Repository jenkinsci/azure-ad-plugin, pull requests merged in 2022-06, with the labels that each got.

#242 Update disable security documentation link
  README.md
Labels: documentation

#247 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#249 Add UPN to authorities
  src/main/java/com/microsoft/jenkins/azuread/AzureAdUser.java
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
Labels: bug

#250 Add group display name as an authority
  src/main/java/com/microsoft/jenkins/azuread/AzureAdUser.java
Labels: bug

#258 Fix for AD users that do not have email addresses
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
Labels: bug
