Repository jenkinsci/azure-ad-plugin, pull requests merged in 2023-12, with the labels that each got.

#480 Allow developer control of parallel testing
  Jenkinsfile
  pom.xml
Labels: chore

#524 Add theme manager integration
  src/main/frontend/index.ts
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config.jelly
  src/main/webapp/css/azure-ad.css
Labels: enhancement

#525 Add support for node properties with people picker for EC2
  src/main/frontend/index.ts
Labels: bug
