Repository jenkinsci/azure-ad-plugin, pull requests merged in 2023-08, with the labels that each got.

#449 Restore select all and unselect all icons
  pom.xml
  src/main/java/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy.java
  src/main/java/com/microsoft/jenkins/azuread/utils/ValidationUtil.java
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config.jelly
  src/main/resources/com/microsoft/jenkins/azuread/table.js
Labels: bug

#450 Delete unused `findbugs-exclude` file
  findbugs-exclude.xml
Labels: chore

#455 Use app specific key discovery url
  src/main/java/com/microsoft/jenkins/azuread/Utils.java
Labels: bug

#456 Update documentation
  README.md
Labels: documentation

#459 Correct graph API Permissions
  README.md
Labels: documentation

#460 Fork matrix-auth into this plugin
  pom.xml
  src/main/java/com/microsoft/jenkins/azuread/AbstractAuthorizationContainerConverter.java
  src/main/java/com/microsoft/jenkins/azuread/AbstractAuthorizationPropertyConverter.java
  src/main/java/com/microsoft/jenkins/azuread/AmbiguityMonitor.java
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationContainer.java
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationContainerDescriptor.java
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationMatrixNodeProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationMatrixProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationPropertyDescriptor.java
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationType.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixFolderProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixNodeProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy.java
  src/main/java/com/microsoft/jenkins/azuread/DeprecationUtil.java
  src/main/java/com/microsoft/jenkins/azuread/GlobalMatrixAuthorizationStrategy.java
  src/main/java/com/microsoft/jenkins/azuread/PermissionEntry.java
  src/main/java/com/microsoft/jenkins/azuread/ValidationUtil.java
  src/main/java/com/microsoft/jenkins/azuread/folder/properties/AuthorizationMatrixProperty.java
  src/main/java/com/microsoft/jenkins/azuread/folder/properties/FolderContributor.java
  src/main/java/com/microsoft/jenkins/azuread/folder/properties/OptionalMarker.java
  src/main/java/com/microsoft/jenkins/azuread/integrations/casc/AzureAdAuthorizationMatrixNodePropertyConfigurator.java
  src/main/java/com/microsoft/jenkins/azuread/integrations/casc/AzureAdMatrixAuthorizationStrategyConfigurator.java
  src/main/java/com/microsoft/jenkins/azuread/integrations/casc/DefinitionEntry.java
  src/main/java/com/microsoft/jenkins/azuread/integrations/casc/MatrixAuthorizationStrategyConfigurator.java
  src/main/java/com/microsoft/jenkins/azuread/integrations/casc/PermissionDefinition.java
  src/main/java/com/microsoft/jenkins/azuread/integrations/casc/PermissionFinder.java
  src/main/resources/com/microsoft/jenkins/azuread/Messages.properties
  src/test/java/com/microsoft/jenkins/azuread/integrations/casc/ConfigAsCodeTest.java
  src/test/resources/com/microsoft/jenkins/azuread/integrations/casc/configuration-as-code-exported.yml
  src/test/resources/com/microsoft/jenkins/azuread/integrations/casc/configuration-as-code.yml
Labels: bug

#461 Mark previous version as incompatible
  pom.xml
Labels: enhancement

#462 Use caffeine for storing instances of GraphClient
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
  src/main/java/com/microsoft/jenkins/azuread/GraphClientCache.java
  src/main/java/com/microsoft/jenkins/azuread/GraphClientCacheKey.java
  src/main/java/com/microsoft/jenkins/azuread/GraphProxy.java
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdLogoutAction/index.jelly
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdLogoutAction/sidepanel.jelly
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/config.jelly
Labels: enhancement

#466 Resolve symbol conflict in job-dsl
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationMatrixProperty.java
  src/main/java/com/microsoft/jenkins/azuread/folder/properties/AuthorizationMatrixProperty.java
Labels: bug
