Repository jenkinsci/azure-ad-plugin, pull requests merged in 2023-09, with the labels that each got.

#470 Fix deprecation warning
  src/main/resources/com/microsoft/jenkins/azuread/table.js
Labels: chore

#471 SECURITY-3227
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
Labels: skip-changelog

#472 Implement nicer property DSL for Job DSL and Pipeline
  README.md
  src/main/frontend/index.ts
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixFolderProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixProperty.java
  src/main/java/com/microsoft/jenkins/azuread/integrations/casc/MatrixAuthorizationStrategyConfigurator.java
  src/test/java/com/microsoft/jenkins/azuread/integrations/casc/ConfigAsCodeTest.java
  src/test/resources/com/microsoft/jenkins/azuread/integrations/casc/configuration-as-code.yml
Labels: enhancement

#395 Clean up Webpack build
  package-lock.json
  package.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: chore

#473 Add type prefix to duplicate user check for azure ad matrix
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config.jelly
  src/main/resources/com/microsoft/jenkins/azuread/Messages.properties
  src/main/resources/com/microsoft/jenkins/azuread/table.js
Labels: bug

#475 Fix missing ambiguity monitor
  src/main/resources/com/microsoft/jenkins/azuread/AmbiguityMonitor/GlobalConfigurationContributor/entries.jelly
  src/main/resources/com/microsoft/jenkins/azuread/AmbiguityMonitor/JobContributor/entries.jelly
  src/main/resources/com/microsoft/jenkins/azuread/AmbiguityMonitor/NodeContributor/entries.jelly
  src/main/resources/com/microsoft/jenkins/azuread/AmbiguityMonitor/index.jelly
  src/main/resources/com/microsoft/jenkins/azuread/AmbiguityMonitor/index.properties
  src/main/resources/com/microsoft/jenkins/azuread/AmbiguityMonitor/message.jelly
  src/main/resources/com/microsoft/jenkins/azuread/AmbiguityMonitor/message.properties
Labels: bug

#485 Fix Matrix Auth user display when user never authenticated
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
Labels: enhancement
