Repository jenkinsci/azure-ad-plugin, pull requests merged in 2024-07, with the labels that each got.

#594 Pass through correct scope per Azure environment
  src/main/java/com/microsoft/jenkins/azuread/GraphClientCache.java
Labels: bug

#596 Add client certificate support
  README.md
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
  src/main/java/com/microsoft/jenkins/azuread/GraphClientCache.java
  src/main/java/com/microsoft/jenkins/azuread/GraphClientCacheKey.java
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/config.jelly
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/help-cacheDuration.html
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/help-clientCertificate.html
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/help-clientId.html
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/help-clientSecret.html
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/help-fromRequest.html
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/help-tenant.html
  src/main/resources/com/microsoft/jenkins/azuread/Messages.properties
  src/test/java/com/microsoft/jenkins/azuread/AzureAdConfigurationSaveTest.java
  src/test/java/com/microsoft/jenkins/azuread/AzureSecurityRealmTest.java
  src/test/java/com/microsoft/jenkins/azuread/integrations/casc/BaseConfigAsCodeTest.java
  src/test/java/com/microsoft/jenkins/azuread/integrations/casc/ConfigAsCodeClientCertificateTest.java
  src/test/java/com/microsoft/jenkins/azuread/integrations/casc/ConfigAsCodeClientSecretTest.java
  src/test/java/com/microsoft/jenkins/azuread/integrations/casc/ConfigAsCodeExportConfigurationTest.java
  src/test/resources/com/microsoft/jenkins/azuread/integrations/casc/ConfigAsCodeTest/config.xml
  src/test/resources/com/microsoft/jenkins/azuread/integrations/casc/configuration-as-code-certificate-auth.yml
  src/test/resources/com/microsoft/jenkins/azuread/integrations/casc/configuration-as-code-secret-auth.yml
Labels: enhancement

#599 Optimize ObjId2FullSidMap::extractObjectId
  src/main/java/com/microsoft/jenkins/azuread/ObjId2FullSidMap.java
  src/test/java/com/microsoft/jenkins/azuread/ObjId2FullSidMapTest.java
Labels: enhancement

#601 Remove yui, cleanup JS
  src/main/resources/com/microsoft/jenkins/azuread/table.js
Labels: developer
