Repository jenkinsci/azure-ad-plugin, pull requests merged in 2025-08, with the labels that each got.

#720 Ban JUnit 4 imports
  pom.xml
Labels: chore

#723 Update authority host for china
  src/main/java/com/microsoft/jenkins/azuread/AzureEnvironment.java
Labels: bug

#724 Update product name to Entra ID in more places
  README.md
  ThirdPartyNotices.txt
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixFolderProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixNodeProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdAuthorizationMatrixProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy.java
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/help-clientId.html
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/help-clientSecret.html
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/help-singleLogout.html
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/help-tenant.html
  src/main/resources/com/microsoft/jenkins/azuread/AzureSecurityRealm/help.html
  src/main/resources/com/microsoft/jenkins/azuread/Messages.properties
Labels: enhancement

#725 Don't include contacts in people picker
  src/main/resources/com/microsoft/jenkins/azuread/AzureAdMatrixAuthorizationStrategy/config.jelly
Labels: bug
