Repository jenkinsci/azure-ad-plugin, pull requests merged in 2025-10, with the labels that each got.

#738 Replaced deprecated stringutils method and minor cleanup
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationContainerDescriptor.java
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationMatrixNodeProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationMatrixProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java
  src/main/java/com/microsoft/jenkins/azuread/GlobalMatrixAuthorizationStrategy.java
  src/main/java/com/microsoft/jenkins/azuread/GraphClientCache.java
  src/main/java/com/microsoft/jenkins/azuread/GraphProxy.java
  src/main/java/com/microsoft/jenkins/azuread/ValidationUtil.java
  src/main/java/com/microsoft/jenkins/azuread/avatar/EntraAvatarProperty.java
  src/main/java/com/microsoft/jenkins/azuread/folder/properties/AuthorizationMatrixProperty.java
Labels: chore

#737 Updated node and npm and ran npm audit fix
  package-lock.json
  pom.xml
Labels: dependencies

#739 Minor Javadoc improvements
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationContainerDescriptor.java
  src/main/java/com/microsoft/jenkins/azuread/AuthorizationProperty.java
  src/main/java/com/microsoft/jenkins/azuread/AzureAuthFailAction.java
  src/main/java/com/microsoft/jenkins/azuread/AzureCachePool.java
  src/main/java/com/microsoft/jenkins/azuread/integrations/casc/MatrixAuthorizationStrategyConfigurator.java
Labels: chore

#736 AzureAdUser#authorities shouldn't be transient
  src/main/java/com/microsoft/jenkins/azuread/AzureAdUser.java
Labels: bug
